name: Install and cache
description: Setup and use node_modules
runs:
  using: 'composite'
  steps:
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
      id: setup-node
    - name: Install dependencies
      run: npm ci
      shell: bash