name: CI-CD
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - build/upgrade-dependencies
    tags:
      - 'v*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - '**'

jobs:
  install:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install
  ci:
    needs: [install]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install
      - name: Turbo CI
        run: npx turbo --continue --single-package ci
