name: Upgrade Dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 6' # at 10am on Saturday

jobs:
  upgrade:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install
      - name: Upgrade dependencies
        run: npx taze major -i -w
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          branch: build/upgrade-dependencies
          title: Upgrade dependencies
          commit-message: 'build: upgrade dependencies'
