name: GitHub Actions
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: ./.github/actions/install
  ci:
    needs: [install]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: ./.github/actions/install
      - name: Turbo CI
        run: npx turbo --continue --single-package ci
